#!/usr/bin/env lua

local lib = require "luaflow_lib"
local cjson = require "cjson"

local sub = string.sub
local encode = cjson.encode
local parse_file = lib.parse_file
local adjust_ctx = lib.adjust_ctx
local print_root_flow = lib.print_root_flow
local opt = {}


local function usage()
    print([=[Usage:
    luaflow [OPTIONS] luafile

OPTIONS:
    -a, --ast       dump AST
]=])
end

local function main()
    if #arg < 1 then
        usage()
        os.exit(0)
    end

    local opt_idx = 1
    for i, v in ipairs(arg) do
        if sub(v, 1, 1) ~= '-' then
            opt_idx = i
            break
        end

        if v == '-a' or v == '--ast' then
            opt.ast = true
        elseif v == '-h' or v == '--help' then
            usage()
            os.exit(0)
        end
    end

    local t, ctx = parse_file(arg[opt_idx])

    if opt.ast then
        print(encode(t))
        return
    end

    adjust_ctx(ctx)
    print_root_flow(ctx)
    --print(encode(t))
    --print(encode(ctx.call))
    --print(encode(ctx.roots))
end

main()
