#!/usr/bin/env lua

local lib = require "luaflow_lib"
local cjson = require "cjson"

local sub = string.sub
local encode = cjson.encode
local parse_file = lib.parse_file
local adjust_ctx = lib.adjust_ctx
local create_ctx = lib.create_ctx
local print_root_flow = lib.print_root_flow
local opt = {}


local function usage()
    print([=[Usage:
    luaflow [OPTIONS] luafile

OPTIONS:
    -a, --ast       dump AST
    -e, --exclude   exclude this list of comma separated functions
    -h, --help      show this help message
]=])
end

local function parse_exclude_list(s)
    local l = {}

    for w in string.gmatch(s, "[%w_%.]+") do
        l[w] = true
    end

    return l
end

local function main()
    if #arg < 1 then
        usage()
        os.exit(0)
    end

    local opt_idx = 1
    local i = 1
    while i <= #arg do
        local v = arg[i]
        if sub(v, 1, 1) ~= '-' then
            opt_idx = i
            break
        end

        if v == '-a' or v == '--ast' then
            opt.ast = true
        elseif v == '-h' or v == '--help' then
            usage()
            os.exit(0)
        elseif v == '-e' or v == '--exclude' then
            if not arg[i + 1] then
                error('expeced exclude list after "' .. arg[i] .. '"')
            end
            opt.exclude = parse_exclude_list(arg[i + 1])
            i = i + 1
        end

        i = i + 1
    end

    local ctx = create_ctx()
    local t = parse_file(ctx, arg[opt_idx])

    if opt.ast then
        print(encode(t))
        return
    end

    adjust_ctx(ctx)
    print_root_flow(ctx, { exclude = opt.exclude })
    --print(encode(t))
    --print(encode(ctx.call))
    --print(encode(ctx.roots))
end

main()
